version: 2.0
jobs:
  build:
    docker:
      - image: mkdryden/avr-toolchain
    steps:
      - checkout
      - run:
          name: CD
          command: cd AVRSolution/Debug
      - run:
          name: ls
          command: ls -al
      - run:
          name: clear
          command: make clean
