version: 2.0
jobs:
  build:
    docker:
      - image: mkdryden/avr-toolchain
    steps:
      - checkout
      - run:
          command: |
            cd AVRSolution/Debug
            ls -al
            make clean

